services:
  backend:
    build: ./backend/api-rest-php
    container_name: backend
    ports:
      - "8080:80"
    volumes:
      - ./backend/api-rest-php:/var/www/html
    networks:
      - app-network
    depends_on:
      - mariadb

  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "8082:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network

  mariadb:
    image: mariadb # Image Docker officielle de MariaDB
    container_name: mariadb
    restart: "no" # Ne pas redémarrer automatiquement le conteneur
    ports:
      - 3306:3306 # Le port 3306 de l'hôte est mappé au port 3306 du conteneur MariaDB
    volumes:
      - ./datadb:/var/lib/mysql # Le répertoire ./datadb est monté pour persister les données de la base de données
    environment:
      MYSQL_ROOT_PASSWORD: super # Mot de passe pour l'utilisateur root
      MYSQL_DATABASE: instacfpt2 # Base de données initiale qui sera créée à la première exécution
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin # Image Docker officielle de phpMyAdmin
    container_name: phpmyadmin
    restart: "no" # Ne pas redémarrer automatiquement le conteneur
    ports:
      - 8081:80  # Le port 8081 de l'hôte est mappé au port 80 du conteneur phpMyAdmin
    environment:
      PMA_HOST: mariadb  # Nom du service MariaDB auquel se connecter
      PMA_PORT: 3306     # Port utilisé par MariaDB
      PMA_USER: root     # Utilisateur root pour la connexion
      PMA_PASSWORD: super  # Mot de passe pour l'utilisateur root
    depends_on: # Dépendance du service phpMyAdmin envers le service MariaDB
      - mariadb
    networks:
      - app-network

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge