# Utiliser une image de Node.js
FROM node:16

# Créer un répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY ./package.json ./package-lock.json ./

# Installer les dépendances de Node.js
RUN npm install

# Copier tout le code source du backend dans le conteneur
COPY . /app

# Exposer le port sur lequel l'application backend s'exécute
EXPOSE 3001

# Exécuter le serveur TypeScript avec ts-node
CMD ["npx", "ts-node", "server.ts"]
