global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3001']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb:3306']

  - job_name: 'mariadb-exporter'
    static_configs:
      - targets: ['mariadb-exporter:9104']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
